export class User {

    public readonly about: string;
    public activity_visible: boolean;
    public age?: number;
    public readonly alert_optout: any[];
    public readonly allow_post_profile: string;
    public readonly allow_receive_news_feed: string;
    public readonly allow_send_personal_conversation: string;
    public readonly allow_view_identities: string;
    public readonly allow_view_profile: string;
    public avatar_urls: { o: any, h: any, l: any, m: any, s: any };
    public profile_banners_urls: any;
    public can_ban: boolean;
    public can_converse: boolean;
    public can_edit: boolean;
    public can_follow: boolean;
    public can_ignore: boolean;
    public can_post_profile: boolean;
    public can_view_profile: boolean;
    public can_warn: boolean;
    public readonly content_show_signature: boolean;
    public readonly creation_watch_state: boolean;
    public custom_fields: string[];
    public custom_title: string;
    public dob: any;
    public readonly email: string;
    public readonly email_on_conversation: boolean;
    public readonly gravatar: string;
    public readonly interaction_watch_state: boolean;
    public is_admin: boolean;
    public is_banned: boolean;
    public is_discouraged: boolean;
    public is_followed: boolean;
    public is_ignored: boolean;
    public is_moderator: boolean;
    public is_super_admin: boolean;
    public last_activity: number;
    public location: string;
    public readonly push_on_conversation: boolean;
    public readonly push_optout: any;
    public readonly receive_admin_email: boolean;
    public secondary_group_ids: number[];
    public readonly show_dob_date: boolean;
    public readonly show_dob_year: boolean;
    public signature: string;
    public readonly timezone: string;
    public readonly use_tfa: any;
    public user_group_id: number;
    public user_state: string;
    public user_title: string;
    public visible: boolean;
    public warning_points: number;
    public website: string;
    public view_url: string;
    public user_id: number;
    public username: string;
    public message_count: number;
    public question_solution_count: number;
    public register_date: number;
    public trophy_points: number;
    public is_staff: boolean;
    public reaction_score: number;
    public vote_score: number;
}